version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: WRU
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: asw0228!!
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  backend:
    build: .
    container_name: backend
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/WRU
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_PASSWORD: asw0228!!
    depends_on:
      - mysql
